### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by asifsomy** [Bluegrams/ScreenRuler#1]
Calculates the wrong number of pixels. I think it is because my display is set to 125%?

**Comment by alxnull** [comment]
As you said, this problem probably is caused by Windows display scaling. Could you specify in which way pixels are different from the correct value? Are they scaled by factor 1.25? And could you add which exact Windows version you are using?

**Comment by neiromaster** [comment]
This is observed on Windows 10. If scaling is set to 125%, then 200px on the screen corresponds to 250px on the ruler.

**Comment by alxnull** [comment]
@Neiromaster Thanks for reporting. ~~If the 200px refer to _scaled_ (logical) pixels this seems to be the intended behaviour as the ruler measures _"physical"_ (unscaled) pixels of the screen.~~ (see below). With scaling set to 125% one scaled pixel equals 1,25 unscaled pixels, thus 200 scaled pixels are measured as 250 unscaled pixels. Please correct me if I'm wrong with this.

(However, this app (as WinForms in general) does have some other UI problems with High-DPI and per-monitor scaling in Windows 10.)

**Comment by neiromaster** [comment]
Yes, you understood correctly. The fact is that I had to look for a replacement for your application, since I often have to work with design and layout.

**Comment by alxnull** [comment]
If this is still relevant to anyone: In v.0.3, the ruler is scaled by Windows and therefore measuring scaled pixels.
