### ISSUE TITLE
not an issue / How to move the Ruler faster?

### ISSUE THREAD

**Issue by shahram7** [Bluegrams/ScreenRuler#10]
Hi there,
first of all i want to thank you very much for your time and energy. i use this app for reading so that i don't lose the lines.
The ruler moves now with arrow keys.
I want to ask if its possible that when I press the down arrow key once, the ruler moves more than now, so that I can start reading the next line?
It would be great if it can move a larger distance at once.
Best Regards

**Comment by alxnull** [comment]
Hi @shahram7,

Glad to hear that this tool is useful to you!
As you mentioned, the ruler can be moved by one pixel in either direction using the arrow keys. For larger steps, you can press `[shift]+[arrow keys]` which will move the ruler by 5px by default. To configure this step size, go to `Settings -> Advanced -> Medium Step Size` and set your desired step size in pixels.
Hope this helps.

P.S.: If you have any further ideas on improving this tool as a reading helper, always feel free to suggest them!

**Comment by shahram7** [comment]
Hi,
Thank you very much for your Help.
No matter what value I enter for the Medium Step, it still moves pixel by
pixel.
I have set background and ticks with the same color and opacity to lowest.
It helps me alot.
It would be greater if we have an option to hide the ticks and lower
opacity like 20%.
Thank you again
Best Regards

**Comment by alxnull** [comment]
Changing the "Medium Step Size" setting only affects the step size of `[shift]+[arrow keys]`, adjusting the step size of the pixel by pixel movement using arrow keys only is currently not possible.
I'll add this and the option to hide the ticks and lower the opacity further to the list of possible enhancements.

**Comment by alxnull** [comment]
@shahram7 Based on your feedback, I have implemented some improvements in v.0.7 of Screen Ruler ([announcement](https://sourceforge.net/p/screenruler/news/2020/08/new-features-in-screen-ruler-07/) | [download](https://sourceforge.net/projects/screenruler/files/v.0.7.0/)), e.g. adjusting the standard step size and hiding the ruler scale. Please check it out!

**Comment by shahram7** [comment]
it couldn't be better.
thank you very much.
