### ISSUE TITLE
can add this feature, thanks

### ISSUE THREAD

**Issue by wjx0912** [Bluegrams/ScreenRuler#13]
![screenruler_feature](https://user-images.githubusercontent.com/5556482/94405349-016ab700-01a3-11eb-8bc2-387b8576e6f7.png)

**Comment by s80s77** [comment]
Unfortunately, this is not answering my question.

Sue Ellen Sopher
Maconaquah Middle School
Project Lead the Way
594 E 800 S
Bunker Hill, IN 46914
765-689-9131 x4308
sophers@maconaquah.k12.in.us

**Comment by alxnull** [comment]
@wjx0912 I already implemented two of your suggestions (1. and 3.). They will be released with the next version. Regarding the other two:
- (2.) What you see is not a gray area _outside_ the ruler but the white marker lines for "0" above and below the gray area (compare that to the white lines at the point labelled with "50". To check this, try to hide the ruler scale or change the color theme.
- (4.) I'll see what can be done about this. Currently, you can track the mouse outside of the ruler if you switch to 2D mode and move the mouse within the area enclosed by the horizontal and vertical ruler.

**Comment by wjx0912** [comment]
@alxnull 
thanks for your reply and great work!
