### ISSUE TITLE
Automatic Screen Resolution Adaptation

### ISSUE THREAD

**Issue by aimilin6688** [Bluegrams/ScreenRuler#28]
1. 我的系统推荐显示器分辨率125%，我要怎么调整尺子才能和我的显示器分辨率一致？
2. 我有两个显示器，显示器A分辨率125%，显示器B分辨率100%，我在这两个显示器移动尺子时候是否可以自动匹配显示器的分辨率？

1. My system recommends 125% resolution of the monitor. How can I adjust the ruler to match the resolution of my monitor?
2. I have two monitors with 125% resolution of Monitor A and 100% resolution of monitor B. Can I automatically match the resolution of the monitor when I move the ruler between the two monitors?
![屏幕截图 2020-11-14 133033](https://user-images.githubusercontent.com/3804814/99140654-9b68bf00-267e-11eb-91b2-8e12f99ca293.png)

**Comment by alxnull** [comment]
Thanks for raising these issues! High-dpi support still is a bit of a problem in this app. There are some differences for measuring pixels or physical units (centimeters, inches etc.):

For centimeters, inches etc. you can adjust the scaling via the _Calibrate ruler_ item in the context menu (`Ctrl+K`). You can set your screen dpi and scaling manually here.

The pixel scale of the app currently should be automatically scaled with Windows, so on a display with 125% scaling, the size of each pixel should scale accordingly. At the moment, there is no built-in way to change this behaviour. I'll look into options for better high-dpi support and automatic adaptation to different monitors.

**Comment by alxnull** [comment]
Hey, I'm currently testing an update that should fix this issue. Please see https://github.com/Bluegrams/ScreenRuler/issues/52 and give feedback if that fixes this issue. Thanks!

**Comment by alxnull** [comment]
Closing this issue with the new updates released in v.0.10.0. Please see http://bluegrams.com/blog/2022/09/display-scaling-and-calibration-with-screenruler.html.
