### ISSUE TITLE
Calibration DPI accepts integer numbers only

### ISSUE THREAD

**Issue by fabian-seiler** [Bluegrams/ScreenRuler#29]
The feature to measure in physical units would be more useful if one could enter the DPI to a higher precision.

On a HP 27z with a DPI of 163.18 (per specification) attempting to enter that, it rounds down to 163 and the centimeter values are off by what i guess is that factor (at the 150% windows screen scaling). It sums up to about half a centimeter over the screen width, so it is not negligible.

**Comment by alxnull** [comment]
Thanks for the suggestion, I'll look into this.

**Comment by alxnull** [comment]
I have added support for floating-point DPI settings in the latest release [v.0.8.1](https://sourceforge.net/p/screenruler/news/2021/01/screen-ruler-updated-to-v081/). Please check if this solves your issue. If not, feel free to reopen this issue. Thanks!

**Comment by fabian-seiler** [comment]
Yes, it works fine now. Thanks a lot!
