### ISSUE TITLE
Marker thickness

### ISSUE THREAD

**Issue by vadim-on-github** [Bluegrams/ScreenRuler#3]
Hello,

Great app! Thanks for the latest update!

It would be great if the marker thickness was 1 pixel, not 2. Or maybe an option in Preferences to set it to either one. When it's 2 it's a bit confusing which side of the marker represents the measurement, the first pixel or the second

**Comment by alxnull** [comment]
Thanks for your feedback and the kind words! Your suggestion (configurable marker thickness) has just been added in 2194638671f1ab6b5a4e0a74d4b5a2d930487432 and will be released with the next update.

**Comment by vadim-on-github** [comment]
Awesome! Thank you so much!!
