### ISSUE TITLE
Ruler calibration is not working

### ISSUE THREAD

**Issue by NinFanBoyFTW** [Bluegrams/ScreenRuler#31]
Hi, I have been trying to calibrate my ruler on my 1080p 27 inch monitor. My DPI is 96 and I am using 100% scale on the monitor, but the measurements do not line up when I put a physical ruler up to the monitor. No matter what settings I put, I cannot get the on screen ruler to line up (in inches) with my real life measuring tape

**Comment by alxnull** [comment]
Hi @NinFanBoyFTW, how far off is the ruler scale from the "real" measuring? In case you can get near the real measurement but the calibration settings aren't precise enough to get a perfect matching, maybe making the DPI settings more precise, as suggested in #29, could solve your issue?

**Comment by PhoenixIV** [comment]
This is how I did it: I opened the calibration dialog and put a ruler on my screen. Then I changed the DPI until it matched my physical ruler.

There is a link in the calibration window, by the way, that leads to a random SourceForge forum page. Would remove this...

**Comment by alxnull** [comment]
Hey, I'm currently testing an update that should fix this issue. Please see https://github.com/Bluegrams/ScreenRuler/issues/52 and give feedback if that fixes this issue. Thanks!

**Comment by alxnull** [comment]
Closing this issue with the new updates released in v.0.10.0. Please see http://bluegrams.com/blog/2022/09/display-scaling-and-calibration-with-screenruler.html.
