### ISSUE TITLE
Feature Req: Keyboard Shortcuts - toggle light/dark & increase/decrease opacity

### ISSUE THREAD

**Issue by minig0d** [Bluegrams/ScreenRuler#33]
Would be great to have a keyboard shortcut for toggling between light and dark mode.

Also would be great to have a shortcut to increase/decrease opacity.

**Comment by alxnull** [comment]
Thanks for your suggestions. I have added both shortcuts in the latest version [v.0.8.1](https://sourceforge.net/p/screenruler/news/2021/01/screen-ruler-updated-to-v081/) with these key combinations:

- `Ctrl+T` for toggling theme
- `Ctrl+"+"/"-"` for increasing/ decreasing opacity
