### ISSUE TITLE
Feature Req: Command Line Configuration / Switches

### ISSUE THREAD

**Issue by minig0d** [Bluegrams/ScreenRuler#34]
Would be great to be able to either:
1) Be able to specify a different config file with a command line parameter (ex. if I had one config I use in one program and another I use with a different, or one for light mode another dark, etc...)
or 
2) Be able to set certain options directly (which override the config file for the session (but don't write to it)) - i.e. if my config is setup with the ruler in dark mode, if I invoke a second instance like "screenruler.exe /light" the second ruler would be in light mode but not change my config file for normal use.

**Comment by alxnull** [comment]
The next update will add the option to load a different config file (of the same format) via `screenruler.exe --config <config_file_path>`.

**Comment by upthekhyber** [comment]
> The next update will add the option to load a different config file (of the same format) via `screenruler.exe --config <config_file_path>`.

Do you have an ETA for the next update? Thanks.
