### ISSUE TITLE
Current mouse position hard to read

### ISSUE THREAD

**Issue by simbalsyd** [Bluegrams/ScreenRuler#35]
The position of the current mouse position can not be read since the normal text on the ruler is in the same place. See figure below

![image](https://user-images.githubusercontent.com/958575/105823775-db70ea00-5fbd-11eb-8bdf-eb71ac17fcd6.png)

![image](https://user-images.githubusercontent.com/958575/105824111-3d315400-5fbe-11eb-99e9-9f86fc93c9a9.png)

I think I already tried all different settings

**Comment by alxnull** [comment]
Thanks for reporting. This was a bug introduced in v.0.8. I have fixed it in the latest version [v.0.8.1](https://sourceforge.net/p/screenruler/news/2021/01/screen-ruler-updated-to-v081/).

**Comment by simbalsyd** [comment]
Thanks. Now it works perfectly!
