### ISSUE TITLE
winget support

### ISSUE THREAD

**Issue by alteredpark** [Bluegrams/ScreenRuler#37]
winget is essentially chocolately. I'd like to add ScreenRuler to the winget repo, but I need the direct download url, any chance of hosting in GH or supplying the direct urls for the versions? TIA

**Comment by alxnull** [comment]
Hi, I'd planned to look into winget myself but haven gotten to it yet :). All the ScreenRuler releases are published to SourceForge currently: https://sourceforge.net/projects/screenruler/files/. Does this suffices for adding to winget?

**Comment by alteredpark** [comment]
Good to see it's on your roadmap 😎 I've done a bit of further reading and it looks like zipped executables / standalone packages are still on the to do [list](https://github.com/microsoft/winget-cli/issues/182) for the winget team, so one to revisit in a bit.
