### ISSUE TITLE
Reverse scale? Zero on right

### ISSUE THREAD

**Issue by 480000** [Bluegrams/ScreenRuler#39]
Many thanks for the software1
I was looking for a scale that could be configured to reverse the scale on a web page.
Cycle racing - shows Km ridden, I want Km to go.
Screen ruler is easily configured to show an identical scale, all I need is for the scale to be reversed. Maximum on left, zero on right.
Any chance? 
Alan

**Comment by alxnull** [comment]
Hey @480000,
thanks for your suggestion. I already implemented the option to reverse the scale. It will be released with the next version.

**Comment by alxnull** [comment]
v.0.9 is now available, so closing this issue for now.

https://sourceforge.net/p/screenruler/news/2021/08/flipping-hypotenuses-angles-and-command-lines-args-with-screen-ruler-v09/
