### ISSUE TITLE
Call "mode" "orientation" instead

### ISSUE THREAD

**Issue by PhoenixIV** [Bluegrams/ScreenRuler#43]
Helloo!

It took me a while to figure out that I can get a vertical ruler with the submenu (DE) "Linealmodus" ("Ruler mode"). I would suggest to call it "orientation" (DE: Ausrichtung) instead. And maybe even add a graphic like ▜ to the name.

The famous "Pixel ruler" is very easy to access in this regard. Especially as changing orientation is the most frequently used function, for me. It is actually pretty unhandy to hide it in a submenu.

**Comment by alxnull** [comment]
Hi @PhoenixIV, thanks for the feedback, will consider renaming it and making the feature clearer to identify.
Regarding accessibility, the easiest way to change the ruler orientation is probably via the keyboard by pressing "Space" instead of going via the context menu.

**Comment by alxnull** [comment]
I believe this issue has been resolved, therefore closing. Please open if you think otherwise.
