### ISSUE TITLE
Enlarge ruler calibration window

### ISSUE THREAD

**Issue by PhoenixIV** [Bluegrams/ScreenRuler#45]
When calibrated with the method I describe in https://github.com/Bluegrams/ScreenRuler/issues/31 using a physical ruler on my screen, It would really help if the calibration window was a little wider. Possibly even making it a floating / changeable width.

**Comment by alxnull** [comment]
Closing this issue with the new updates released in v.0.10.0. Please see http://bluegrams.com/blog/2022/09/display-scaling-and-calibration-with-screenruler.html.
