### ISSUE TITLE
Yellow current measurement and green side measurement numbers intersect; unreadable

### ISSUE THREAD

**Issue by PhoenixIV** [Bluegrams/ScreenRuler#46]
![intersect](https://user-images.githubusercontent.com/2091755/137383690-8331e9e3-6ff5-46e8-90b7-2748aec5b0d0.png)

There is no colour setting for the green measurements on the side. I would like to disable them. They make it hard to read the number in yellow. Maybe put them on different heights or hide the side measurement (most elegant solution?) when the cursor is near the side of the ruler.

**Comment by alxnull** [comment]
Hey @PhoenixIV, you can disable the green labels on both ends of the ruler by unchecking `Appearance -> Show Offset and Length` in the context menu.

**Comment by PhoenixIV** [comment]
Ah, I see! Thanks.
Why not double these settings into the "settings" dialogue?

I would still keep this ticket open, as I think it is a good remark that this overlapping is not well solved at the moment. Possible solutions:

- Adding different heights
- Letting the yellow number stop before the green one (while still moving the line)
- Make the green number disappear in case of overlapping (if I want to read it I can just move my cursor aside)
