### ISSUE TITLE
Ruler shows pixels incorrectly on 2560x440 monitor

### ISSUE THREAD

**Issue by Stedioz** [Bluegrams/ScreenRuler#51]
Below is a ruler with the correct length
![ruler](https://user-images.githubusercontent.com/87002550/143386909-a419a759-d9c7-4f3c-a84f-3dcd5a6ac1ea.jpg)
.

**Comment by Stedioz** [comment]
2560 x 1440

**Comment by alxnull** [comment]
Hey, I'm currently testing an update that should fix this issue. Please see #52 and give feedback if that fixes this issue. Thanks!

**Comment by alxnull** [comment]
Closing this issue with the new updates released in v.0.10.0. Please see http://bluegrams.com/blog/2022/09/display-scaling-and-calibration-with-screenruler.html.
