### ISSUE TITLE
add the ruler to the taskbar

### ISSUE THREAD

**Issue by d4e666** [Bluegrams/ScreenRuler#55]
I have the screenruler pinned to my taskbar. However when I click it to open, a new rules gets opened on each click. Can every ruler be added to the taskbar just like regular programs to avoid multiple instances from opening when only 1 active instance is needed(multi instance is ok, just show that there are active ones)

**Comment by alxnull** [comment]
I believe what you would like to achieve can be configured in the settings as follows: Settings -> Advanced -> Miscellaneous -> Uncheck "Show icon in notification area"

**Comment by alxnull** [comment]
Closing, please reopen if this hasn't be resolved.
