### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by lzporter** [Bluegrams/ScreenRuler#6]
Hi，Bluegrams，thank you for your awesome work，especially for the new 0.5 version which added calibrate Ruler。I am a beginner  for winform. When you released the 0.5* version 30 minutes ago, I just finished the software localization of 0.4 version. After a few days, I will finish the localization of the new version. Sorry I don’t use much of git. I need to be familiar with it. When i finish it，I will pull for merge。

**Comment by alxnull** [comment]
Hi,
thanks for your interest in this software. I really appreciate your 
efforts to translate the tool into Chinese. If you need any help during 
the localization process, feel free to ask.

Alex

**Comment by alxnull** [comment]
@lzporter For the next version (v.0.6), some new features have been added to the ruler. Since you contributed the Chinese translations to this app, I'd be very glad if you could help again updating them to the newest version.
