### ISSUE TITLE
There is a Trojan in the zipped folder

### ISSUE THREAD

**Issue by Aldo-aldo** [Bluegrams/ScreenRuler#63]
Analyzing the folder downloaded from Sourceforge with Virustotal, a trojan was found in the zipped folder
![Immagine 2024-08-05 195426](https://github.com/user-attachments/assets/f56163a7-3679-4709-86d3-2d737359870e)

**Comment by FoxGos** [comment]
![Ekran görüntüsü 2024-12-08 025812](https://github.com/user-attachments/assets/67498d94-3a3b-4797-ace2-9fe159fc12ac)

Me to it's the .exe file

**Comment by alxnull** [comment]
Hey @Aldo-aldo,

unfortunately, a virus scanner might sometimes incorrectly flag files as dangerous that in reality is not. Looking at VirusTotal, the other >60 virus scanners did not detect the zip as malware, which makes it pretty safe that the one flagging it is incorrect. Additionally, all files uploaded to SourceForge are automatically scanned for malware on the platform, so in general it's unlikely that malware is distributed via this platform.

If still you don't trust the downloaded zip, there are two other alternatives:
- install it via chocolatey, which also scans packages for malware on its platform
- ScreenRuler is open-source, so to be extra sure, please clone the code and build the binary yourself from the repo. This will result in a binary functionally identical to the one downloaded from SourceForge

Hope this helps!
